baseURL = "/"
theme = "hugo-whisper-theme"
languageCode = "en-us"
title = "Journey Migrations"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[caches]
  [caches.images]
    dir = ":cacheDir/images"
    
# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Journey is a script based database migration tool providing on stepwise changes.'
  homepage_image = '/images/route.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Journey is a script based database migration tool providing on stepwise changes."
    meta_og_title = "Journey Migrations"
    meta_og_type = "website"
    meta_og_url = "https://journey.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Journey is a script based database migration tool providing on stepwise changes."
    meta_twitter_card = "summary"
    meta_twitter_site = "@journey"
    meta_twitter_creator = "@journey"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.png"

  [params.footer]
    copyright_text = 'Free Hugo theme by <a class="zerostatic" href="https://www.zerostatic.io">Zerostatic Themes</a>'
